### ISSUE TITLE
Bot not sending command responses

### ISSUE THREAD

**Issue by PhantomNimbi** [weebsquad/pyboat#104]
Yo I'm trying to get PyBoat up and running in my own server and it's not doing anything at all. Here is my console log if it helps:

```yml
(!) Plugin typescript: @rollup/plugin-typescript TS2367: This condition will always return 'false' since the types 'Type' and '20' have no overlap.
src/modules/admin.ts: (214:65)

214       if (message.webhookId !== null || (message.application && message.type === 20)) {
                                                                    ~~~~~~~~~~~~~~~~~~~

created ./dist/bundle.js in 10.8s

> pyboat@1.8.10 publish
> node cd/publish.js

[ '180734778465587200' ] [] [] []
Published to Developer Corner (801125364218200074) successfully (Revision 530)!
WS Open
PYLON LOG: No config
PYLON LOG: loading language files
PYLON LOG: Initialized on VM (config loaded) Cpu time so far: 15ms
PYLON LOG: Executed modules for a MESSAGE_CREATE event. -- CPU Time so far: 2ms
```

The only thing it does when i attempt a command is put this into the console log:

```yml
PYLON LOG: Executed modules for a MESSAGE_CREATE event. -- CPU Time so far: 2ms
```

There is no response at all in Discord.

Here is my `config.json` if it helps:

```yml
{
  "guildId": "801125364218200074",
  "language": "en_US",
  "levels": {
    "roles": [
      {
        "__key": "801125364252147744",
        "level": 999
      },
      {
        "__key": "801125364252147743",
        "level": 500
      },
      {
        "__key": "801160627283689512",
        "level": 250
      }
    ],
    "users": [
      {
        "__key": "465228604721201158",
        "level": 999
      },
      {
        "__key": "240260165054496769",
        "level": 999
      },
      {
        "__key": "397666065066491905",
        "level": 999
      }
    ]
  },
  "modules": {
    "queue": true,
    "admin": {
      "enabled": true,
      "roleAliases": [
        {
          "__key": "801125364252147744",
          "alias": "Admin"
        },
        {
          "__key": "801125364252147743",
          "alias": "Mod"
        },
        {
          "__key": "801160627283689512",
          "alias": "Helper"
        }
      ],
      "groupRoles": [
        {
          "__key": "845133424452304917",
          "alias": "Developer"
        },
        {
          "__key": "867815395129294868",
          "alias": "Errite"
        },
        {
          "__key": "867927746918092871",
          "alias": "MountainT Development"
        },
        {
          "__key": "867927118724599818",
          "alias": "Discord"
        },
        {
          "__key": "867926859407589377",
          "alias": "Virtual Customs"
        },
        {
          "__key": "867928037952487494",
          "alias": "Black Dragons Gaming"
        },
        {
          "__key": "867927928929919046",
          "alias": "Barcode Gaming"
        },
        {
          "__key": "867927824797954138",
          "alias": "Sports Empire"
        },
        {
          "__key": "867930129890947083",
          "alias": "The Fur Den"
        }
      ],
      "lockedRoles": [
        "801894337418887249"
      ],
      "defaultRole": "801125364252147744",
      "persist": {
        "enabled": true,
        "levels": [
          {
            "__key": 1,
            "roles": true,
            "nick": true,
            "mute": true,
            "deaf": true,
            "channels": true,
            "roleIncludes": [
              "801125364252147744",
              "801125364252147743",
              "801160627283689512",
              "801125364243234854",
              "867815395129294868",
              "867927746918092871",
              "867926859407589377",
              "867928037952487494",
              "867927928929919046"
            ],
            "roleExcludes": []
          }
        ],
        "saveOnBan": false
      },
      "autoroles": {
        "enabled": true,
        "human": [
          "801125364218200076"
        ],
        "bot": [
          "862949652029505566"
        ]
      },
      "reactroles": {
        "enabled": true,
        "definitions": [
          {
            "role": "834298941789044746",
            "message": "873723264671842365",
            "emoji": "<a:MusicBeat:845652681066414160>",
            "type": "toggle"
          },
          {
            "role": "830384201944793118",
            "message": "873723264671842365",
            "emoji": "<a:giggity:870765649415241788>",
            "type": "toggle"
          },
          {
            "role": "834279815119896597",
            "message": "873723264671842365",
            "emoji": "<a:BlackCrystalHeart:870769145422155826>",
            "type": "toggle"
          }
        ]
      },
      "autoPrune": {
        "enabled": true,
        "channels": [
          {
            "__key": "834488332624461896",
            "duration": "1h"
          },
          {
            "__key": "801125365384871973",
            "duration": "1h"
          },
          {
            "__key": "824240684893995018",
            "duration": "1h"
          },
          {
            "__key": "845276798891851776",
            "duration": "1h"
          },
          {
            "__key": "867923681735757895",
            "duration": "1h"
          }
        ]
      },
      "voiceLink": {
        "enabled": true,
        "global": "858520350551048212",
        "channels": [
          {
            "__key": "801125365896445982",
            "text_channel": "824240684893995018"
          },
          {
            "__key": "845470773673328670",
            "text_channel": "867923681735757895"
          },
          {
            "__key": "801125366277603388",
            "text_channel": "845276798891851776"
          },
          {
            "__key": "851318573645561857",
            "text_channel": "873724375248027670"
          }
        ]
      }
    },
    "antiPing": {
      "enabled": true,
      "caughtMessages": [],
      "actualCaughtMessage": "Don't ping staff members directly! If you need help, ping one of our staff roles.",
      "instaDeletePings": true,
      "banOnLeave": true,
      "pingsForAutoMute": 5,
      "staff": 999,
      "emojiActions": [
        {
          "__key": "👌",
          "action": "IgnoreOnce"
        },
        {
          "__key": "✔️",
          "action": "Ignore"
        },
        {
          "__key": "🔇",
          "action": "Mute"
        },
        {
          "__key": "👢",
          "action": "Softban"
        },
        {
          "__key": "🔨",
          "action": "Ban"
        }
      ],
      "bypass": {
        "level": 50,
        "users": [],
        "roles": [
          "801125364252147744",
          "862949652029505566",
          "801125364252147743",
          "801160627283689512"
        ]
      },
      "targets": {
        "users": {
          "include": [
            "465228604721201158",
            "240260165054496769",
            "397666065066491905"
          ],
          "exclude": []
        },
        "roles": {
          "include": [],
          "exclude": []
        },
        "channels": {
          "include": [],
          "exclude": []
        },
        "categories": {
          "include": [],
          "exclude": []
        }
      }
    },
    "antiSpam": {
      "enabled": true,
      "antiRaid": [],
      "antiRaidPingRole": "801125364252147744",
      "antiRaidPingChannel": "862946424836325376",
      "channels": [],
      "categories": [],
      "levels": [
        {
          "__key": 50,
          "stop": false,
          "clean": true,
          "cleanDuration": 0,
          "action": "TEMPMUTE",
          "actionDuration": "30m",
          "characters": "750/4",
          "messages": "6/4",
          "newlines": "20/4",
          "emoji": "40/4",
          "attachments": "4/10",
          "links": "4/10",
          "duplicateMessages": "3/10"
        }
      ]
    },
    "censor": {
      "enabled": true,
      "nameChecks": [],
      "channels": [],
      "categories": [],
      "levels": [
        {
          "__key": 50,
          "stop": false,
          "violations": {
            "trigger": "2/5",
            "action": "TEMPMUTE",
            "actionDuration": "30m"
          },
          "globalViolations": {
            "trigger": "2/5",
            "actionDuration": "30m",
            "actionValue": 5
          },
          "invites": {
            "self": true,
            "vanityUrl": false,
            "whitelist": {
              "codes": [],
              "guilds": []
            },
            "blacklist": {
              "codes": [],
              "guilds": []
            }
          },
          "urls": {
            "allowSubdomains": false,
            "whitelist": [],
            "blacklist": []
          },
          "zalgo": true,
          "words": [
            "fuck",
            "cunt",
            "dick",
            "ass",
            "asshole",
            "bitch",
            "biatch",
            "fag",
            "faggot",
            "queer",
            "slut",
            "dike",
            "cracka"
          ],
          "tokens": [],
          "caps": {
            "minLength": 1,
            "followed": 10,
            "percentage": 75
          },
          "chars": {
            "limit": 1000,
            "newLines": 20,
            "nonAscii": true
          },
          "regex": []
        }
      ]
    },
    "commands": {
      "enabled": true,
      "prefix": [
        "~",
        ";",
        ".",
        "p.",
        "p!"
      ],
      "allowMentionPrefix": true,
      "hideNoAccess": true,
      "duplicateRegistry": true,
      "overrides": []
    },
    "counting": {
      "enabled": true,
      "channels": [
        "873731715594604555"
      ],
      "autoPins": {
        "single": [],
        "repeating": [],
        "repeatingLast": []
      },
      "useWebhook": true,
      "webhook": "https://discord.com/api/webhooks/873731734007590943/lk8eA69OdpIny_iQqpAW4uHaNxjpytKaYgvsQfbkmEpBGphKQv4zRh9CmCCeHG2Rl-A8"
    },
    "customCode": {
      "enabled": false
    },
    "infractions": {
      "enabled": true,
      "checkLogs": true,
      "integrate": true,
      "muteRole": "801125364218200075",
      "defaultDeleteDays": 7,
      "targeting": {
        "reqDiscordPermissions": {
          "KICK_MEMBERS": true,
          "BAN_MEMBERS": true,
          "MANAGE_ROLES": true,
          "MANAGE_MESSAGES": true,
          "MANAGE_NICKNAMES": true
        },
        "checkLevels": true,
        "checkRoles": true,
        "allowSelf": false,
        "othersEditLevel": 250
      },
      "confirmation": {
        "reaction": true,
        "message": true,
        "expiry": 5,
        "deleteOriginal": true
      }
    },
    "logging": {
      "enabled": true,
      "auditLogs": true,
      "logChannels": [
        {
          "__key": "844734009623445514",
          "embed": true,
          "description": "Server Logs",
          "embedColor": "#0080c0",
          "footerAvatar": "https://avatars.githubusercontent.com/u/56440847?s=280&v=4",
          "webhookUrl": "https://discord.com/api/webhooks/873712481602768907/iU8-dZjp1UcxvBj6S9fS2lqLhtJ2uagUy-9PXyjy80wKl3t2HpmeQo6o_lzCfdMpg3Z2",
          "showEventName": true,
          "showTimestamps": true,
          "scopes": {
            "include": [
              "*"
            ],
            "exclude": []
          }
        }
      ],
      "ignores": {
        "channels": [],
        "users": [],
        "self": true,
        "selfAuditLogs": true,
        "extendUsersToAuditLogs": true,
        "blacklistedUsers": true,
        "logChannels": true
      },
      "userTag": "{MENTION}",
      "actorTag": "{MENTION}",
      "suffixReasonToAuditlog": true,
      "reasonSuffix": " with reason `{REASON_RAW}`",
      "timezone": "Etc/GMT+0"
    },
    "reddit": {
      "enabled": false
    },
    "starboard": {
      "enabled": true,
      "channels": [
        {
          "__key": "839870624225820682",
          "emoji": "⭐",
          "maxEmoji": "🌟",
          "clearOnDelete": true,
          "clearOnModDelete": true,
          "minReacts": 5,
          "minReactsPin": 30,
          "maxReacts": 30,
          "messageLifetime": 24,
          "preventSelf": true,
          "noStats": false,
          "sources": [],
          "ignores": []
        }
      ]
    },
    "tags": {
      "enabled": true,
      "maxLength": 200,
      "levelEditOthers": 50
    },
    "translation": {
      "enabled": false
    },
    "utilities": {
      "enabled": true,
      "snipe": {
        "enabled": true,
        "delay": 5
      },
      "customUserRoles": {
        "enabled": true,
        "clearOnKick": true,
        "clearOnBan": true,
        "clearOnLeave": true
      }
    }
  }
}
```

I tried asking for help in your Discord but your bot muted me....
